spring:
  datasource:
    url: jdbc:h2:mem:testdb1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework: DEBUG